<a href="https://colab.research.google.com/github/brycebanton/Linear_Algebra_Projects/blob/main/SolvingSystems_RREF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
from numpy import c_

ll = "loaded"

In [3]:
lll = " correctly!"

def rref(matrix):
    A = np.array(matrix, dtype=np.float64)
    
    r = 0 #row
    c = 0 #column

    (maxr, maxc) = A.shape

    prev_row_pivot = -1   # The previous row with a leading term:
    tmp_pivot_row = -1
    this_pivot_row = -1

    for c in range(maxc):  # go through each column
      tmp_pivot_row = -1  # reset the tmp pivot row
      this_pivot_row = -1  # reset this pivot row
      for r in range(maxr):  # Find the leading term in this column below prev_row_pivot
        if ((r > prev_row_pivot) and (A[r][c] != 0.0)):
          tmp_pivot_row = r  # find the new pivot row
      if (tmp_pivot_row > -1):  # we found a candidate for the leading term:
        #swap row this_pivot_row with (prev_row_pivot + 1)
        A[[tmp_pivot_row, prev_row_pivot+1]] = A[[prev_row_pivot + 1, tmp_pivot_row]]
        #set this_pivot_row to prev_row_pivot+1
        this_pivot_row = prev_row_pivot + 1
        #Now, normalize the row based on the pivot value:
        A[ this_pivot_row ] = A[ this_pivot_row ] / A[ this_pivot_row ][c]
        #Then, use this row to force 0's above and below the pivot entry:
        #subtract multiples of of the this_pivot_row row from the others
        for r_ in range(len(A)):
            if r_ != this_pivot_row:
                A[r_] = A[r_] - A[this_pivot_row] * A[r_][c] / A[this_pivot_row][c]
        prev_row_pivot = this_pivot_row
    return A    
    
    

print(">> The page ", ll, lll)

>> The page  loaded  correctly!


In [4]:
# create the matrix:
A = np.matrix([[5, 6, 2],
               [4, 7, 19],
               [0, 3, 12]])

# create the vector for the right hand side:
b = np.matrix([[-1], [2], [1]])

In [5]:
print(A)

[[ 5  6  2]
 [ 4  7 19]
 [ 0  3 12]]


In [6]:
print(b)

[[-1]
 [ 2]
 [ 1]]


In [7]:
M = np.c_[A,b]
print(M)

[[ 5  6  2 -1]
 [ 4  7 19  2]
 [ 0  3 12  1]]


np.c_ is concatenating the matrices together which is shown in M

In [8]:
rref(M)

array([[ 1.        ,  0.        ,  0.        ,  0.45736434],
       [ 0.        ,  1.        ,  0.        , -0.62790698],
       [-0.        , -0.        ,  1.        ,  0.24031008]])

rref is the function described above

#Solving and checking work from prior homework




$$
(a) \hspace{.5cm}
\left\{ \begin{array}{rcr} 2x + 2y & = & 5 \\ x - 4y & = & 0 \\ \end{array} \right.
\hspace{1cm}
(b) \hspace{.5cm}
\left\{ \begin{array}{rcr} -x + y &=& 1 \\ x + y &=& 2 \\ \end{array}
\right.
\hspace{1cm}
(c) \hspace{.5cm}
\left\{ \begin{array}{rcr} x - 3y + z & = 1 \\ x + y + 2z & = & 14 \\ \end{array}
\right.
\hspace{1cm}
(d) \hspace{.5cm}
\left\{ \begin{array}{rcr} -x - y &=& 1 \\ -3x -3 y &=& 2 \\ \end{array}
\right.
$$


$$
(e) \hspace{.5cm}
\left\{ \begin{array}{rcr} 4y + z & = & 20 \\ 2x - 2y + z & = & 0 \\ x + z & = & 5 \\ x + y - z & = & 10 \\ \end{array} \right.
\hspace{1cm}
(f) \hspace{.5cm}
\left\{ \begin{array}{rcr} 2x + z + w & = & 5 \\ y - w & = & -1 \\ 3x - z - w & = & 0 \\ 4x + y + 2z + w & = & 9 \\ \end{array}
\right.
$$



In [13]:
# create the matrix:
A = np.matrix([[2, 2],
               [1, -4]])

# create the vector for the right hand side:
b = np.matrix([[5], [0]])

### Solving for problem A

In [14]:
print(A)

[[ 2  2]
 [ 1 -4]]


In [15]:
print(b)

[[5]
 [0]]


In [16]:
matr = np.c_[A,b]
print(matr)

[[ 2  2  5]
 [ 1 -4  0]]


In [17]:
rref(matr)

array([[1. , 0. , 2. ],
       [0. , 1. , 0.5]])

## Solving for problem B

In [18]:
# create the matrix:
A = np.matrix([[-1, 1],
               [1, 1]])

# create the vector for the right hand side:
b = np.matrix([[1], [2]])

In [19]:
print(A)

[[-1  1]
 [ 1  1]]


In [20]:
print(b)

[[1]
 [2]]


In [21]:
matr = np.c_[A,b]
print(matr)

[[-1  1  1]
 [ 1  1  2]]


In [22]:
rref(matr)

array([[1. , 0. , 0.5],
       [0. , 1. , 1.5]])

## Solving for Problem C

In [23]:
# create the matrix:
A = np.matrix([[1, -3, 1],
               [1, 1, 2]])

# create the vector for the right hand side:
b = np.matrix([[1], [14]])

In [24]:
print(A)

[[ 1 -3  1]
 [ 1  1  2]]


In [25]:
print(b)

[[ 1]
 [14]]


In [26]:
matr = np.c_[A,b]
print(matr)

[[ 1 -3  1  1]
 [ 1  1  2 14]]


In [28]:
rref(matr)

array([[ 1.  ,  0.  ,  1.75, 10.75],
       [-0.  ,  1.  ,  0.25,  3.25]])

## Solving for Problem D

In [70]:
# create the matrix:
A = np.matrix([[-1, -1],
               [-3, -3]])

# create the vector for the right hand side:
b = np.matrix([[1], [2]])
print(A)
print(b)

[[-1 -1]
 [-3 -3]]
[[1]
 [2]]


In [71]:
matr = np.c_[A,b]
print(matr)

[[-1 -1  1]
 [-3 -3  2]]


In [72]:
answ = rref(matr)
answ

array([[1., 1., 0.],
       [0., 0., 1.]])

This is no solution because 0 != 1

## Solving for Problem E

In [115]:
# create the matrix:
A = np.matrix([[0, 4, 1],
               [2, -2, 1],
               [1, 0, 1],
               [1, 1, -1]])

# create the vector for the right hand side:
b = np.matrix([[20], [0], [5], [10]])
print(A)
print(b)

[[ 0  4  1]
 [ 2 -2  1]
 [ 1  0  1]
 [ 1  1 -1]]
[[20]
 [ 0]
 [ 5]
 [10]]


In [116]:
matr = np.c_[A,b]
print(matr)

[[ 0  4  1 20]
 [ 2 -2  1  0]
 [ 1  0  1  5]
 [ 1  1 -1 10]]


In [117]:
answ =rref(matr)
answ

array([[1., 0., 0., 5.],
       [0., 1., 0., 5.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.]])

In [118]:
for i in range(len(answ)):
  constants = answ[i, len(answ)-1]
  print(constants)

5.0
5.0
0.0
0.0


## Solving for Problem F

In [47]:
A = np.matrix([[2, 0, 1, 1],
               [0, 1, 0, -1],
               [3, 0, -1, -1],
               [4, 1, 2, 1]])

# create the vector for the right hand side:
b = np.matrix([[5], [-1], [0], [9]])
print(A)
print(b)

[[ 2  0  1  1]
 [ 0  1  0 -1]
 [ 3  0 -1 -1]
 [ 4  1  2  1]]
[[ 5]
 [-1]
 [ 0]
 [ 9]]


In [48]:
matr = np.c_[A,b]
print(matr)

[[ 2  0  1  1  5]
 [ 0  1  0 -1 -1]
 [ 3  0 -1 -1  0]
 [ 4  1  2  1  9]]


In [49]:
rref(matr)

array([[ 1.,  0.,  0.,  0.,  1.],
       [-0.,  1.,  0., -1., -1.],
       [-0., -0.,  1.,  1.,  3.],
       [ 0.,  0.,  0.,  0.,  0.]])